name: Rust CI for Multiple Projects

on:
  push:
    branches:
      - main  # Runs on push to the main branch
      - 'feature/*'  # Runs on feature branches
  pull_request:
    branches:
      - main   # Runs on pull request to the main branch

jobs:
  # Job for project 1
  data_types:
    runs-on: ubuntu-latest  # You can change this to any OS you'd like
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust for project 1
        uses: actions/setup-rust@v1

      - name: Install dependencies for project 1
        run: |
          cd project-1
          cargo fetch  # Fetch dependencies for project-1

      - name: Run tests for project 1
        run: |
          cd project-1
          cargo test

      - name: Build project 1
        run: |
          cd project-1
          cargo build --release

  # Job for project 2
  Example_Projects/number_sorter:
    runs-on: ubuntu-latest  # Same as above
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust for project 2
        uses: actions/setup-rust@v1

      - name: Install dependencies for project 2
        run: |
          cd project-2
          cargo fetch  # Fetch dependencies for project-2

      - name: Run tests for project 2
        run: |
          cd project-2
          cargo test

      - name: Build project 2
        run: |
          cd project-2
          cargo build --release